"""MuJoCo 本地最小类型桩（官方包未提供 .pyi）。

只覆盖本项目用到的 API；未列出的属性通过 __getattr__ 回退为 Any，
避免 Pylance/Pyright 把 mujoco 的动态导出报成“无法解析”。
"""

from typing import Any


class Renderer:
    def __init__(self, model: Any, height: int, width: int) -> None: ...
    def update_scene(self, data: Any, camera: str | None = None) -> None: ...
    def render(self) -> Any: ...
    def close(self) -> None: ...
    def __enter__(self) -> Renderer: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...


def mj_forward(model: Any, data: Any) -> None: ...
def mj_step(model: Any, data: Any) -> None: ...
def mj_resetData(model: Any, data: Any) -> None: ...
def mj_name2id(model: Any, objtype: Any, name: str) -> int: ...


def __getattr__(name: str) -> Any: ...
